//----------------------------------------------------------------
// AutoGenerated sap1 srm regblock.
//----------------------------------------------------------------

`ifndef INCLUDED_Sap1_svh
`define INCLUDED_Sap1_svh
  //------------------------------------------------------
  // Regblock Sap1 
  //------------------------------------------------------
  class Sap1 extends srm_node;
  BlockA blockA;

  function new(string name, srm_node parent);
    super.new(name, parent);
    blockA = new(.name("blockA_node_inst"), .parent(this));
    add_child(blockA);
    blockA.set_offset("default", .offset('ha000_0000));
  endfunction

  endclass: Sap1

`endif
